# Generated by Django 3.1.6 on 2021-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60, verbose_name='название')),
                ('anons', models.CharField(default='', max_length=250, verbose_name='предисловие')),
                ('full_text', models.TextField(verbose_name='полный-текст')),
            ],
        ),
    ]
